<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CompetitionSeeder extends Seeder
{
    public function run(): void
    {
        $felicia = DB::table('users')->where('email', 'felicia@competehub.com')->value('id');
        $valentino = DB::table('users')->where('email', 'valentino@competehub.com')->value('id');

        $judgeScoreId = DB::table('scoring_types')->where('name', 'Judge Score')->value('id');
        $timeBasedId = DB::table('scoring_types')->where('name', 'Time Based')->value('id');
        $hybridScoreId = $judgeScoreId; // Fallback since hybrid doesn't exist in seeders

        $competitions = [
            [
                'uuid'               => Str::uuid(),
                'user_id'            => $valentino,
                'name'               => 'Hackathon Nasional 2025',
                'description'        => 'Kompetisi membuat aplikasi inovatif dalam waktu 48 jam.',
                'type'               => 'team',
                'category'           => 'Web Development',
                'submission_mode'    => 'captain_only',
                'banner_url'         => 'banners/hackathon_banner.png',
                'scoring_type_id'    => $hybridScoreId,
                'registration_fee'   => 150000,
                'quota'              => 50,
                'start_date'         => '2026-06-01',
                'end_date'           => '2026-06-03',
                'registration_start' => '2026-05-01',
                'registration_end'   => '2026-05-28',
                'status'             => 'open',
                'rules'              => "1. Tim terdiri dari 3 orang\n2. Karya harus orisinal",
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'uuid'               => Str::uuid(),
                'user_id'            => $felicia,
                'name'               => 'Competitive Programming Cup',
                'description'        => 'Lomba pemrograman kompetitif perorangan, skor berdasarkan kecepatan.',
                'type'               => 'individual',
                'category'           => 'Competitive Programming',
                'submission_mode'    => 'captain_only',
                'banner_url'         => 'banners/cp_banner.png',
                'scoring_type_id'    => $timeBasedId,
                'registration_fee'   => 0,
                'quota'              => 100,
                'start_date'         => '2026-07-10',
                'end_date'           => '2026-07-11',
                'registration_start' => '2026-06-01',
                'registration_end'   => '2026-07-05',
                'status'             => 'open',
                'rules'              => "1. Dilarang menyalin kode\n2. Bahasa: C++, Java, Python",
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'uuid'               => Str::uuid(),
                'user_id'            => $valentino,
                'name'               => 'UI/UX Design Competition',
                'description'        => 'Kompetisi desain UI/UX untuk tim mahasiswa.',
                'type'               => 'team',
                'category'           => 'UI/UX Design',
                'submission_mode'    => 'captain_only',
                'banner_url'         => 'banners/uiux_banner.png',
                'scoring_type_id'    => $judgeScoreId,
                'registration_fee'   => 75000,
                'quota'              => null,
                'start_date'         => '2026-08-15',
                'end_date'           => '2026-08-20',
                'registration_start' => '2026-07-01',
                'registration_end'   => '2026-08-10',
                'status'             => 'open',
                'rules'              => "1. Tema: Edukasi\n2. Hasil akhir berupa prototype",
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'uuid'               => Str::uuid(),
                'user_id'            => $felicia,
                'name'               => 'Siber Defense CTF 2026',
                'description'        => 'Kompetisi Capture The Flag tingkat nasional.',
                'type'               => 'team',
                'category'           => 'Capture The Flag',
                'submission_mode'    => 'all_members',
                'banner_url'         => null,
                'scoring_type_id'    => $timeBasedId,
                'registration_fee'   => 100000,
                'quota'              => 40,
                'start_date'         => '2026-09-01',
                'end_date'           => '2026-09-02',
                'registration_start' => '2026-08-01',
                'registration_end'   => '2026-08-25',
                'status'             => 'open',
                'rules'              => "1. Tidak boleh merusak infrastruktur CTF\n2. Flag format: CTF{...}",
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'uuid'               => Str::uuid(),
                'user_id'            => $valentino,
                'name'               => 'Data Science Challenge 2026',
                'description'        => 'Tantangan prediksi data menggunakan machine learning.',
                'type'               => 'individual',
                'category'           => 'Other',
                'submission_mode'    => 'captain_only',
                'banner_url'         => null,
                'scoring_type_id'    => $judgeScoreId,
                'registration_fee'   => 50000,
                'quota'              => null,
                'start_date'         => '2026-05-20',
                'end_date'           => '2026-05-30',
                'registration_start' => '2026-04-01',
                'registration_end'   => '2026-05-15',
                'status'             => 'ongoing',
                'rules'              => "1. Dataset disediakan panitia\n2. Penilaian berdasar akurasi",
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'uuid'               => Str::uuid(),
                'user_id'            => $felicia,
                'name'               => 'IoT Innovation Cup 2025',
                'description'        => 'Kompetisi proyek Internet of Things untuk solusi kota pintar.',
                'type'               => 'team',
                'category'           => 'Other',
                'submission_mode'    => 'captain_only',
                'banner_url'         => null,
                'scoring_type_id'    => $hybridScoreId,
                'registration_fee'   => 200000,
                'quota'              => 20,
                'start_date'         => '2025-10-01',
                'end_date'           => '2025-10-15',
                'registration_start' => '2025-08-01',
                'registration_end'   => '2025-09-15',
                'status'             => 'finished',
                'rules'              => "1. Komponen IoT bebas\n2. Presentasi via Zoom",
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'uuid'               => Str::uuid(),
                'user_id'            => $valentino,
                'name'               => 'Mobile App Dev Arena',
                'description'        => 'Arena pengembangan aplikasi mobile terbaik.',
                'type'               => 'team',
                'category'           => 'Web Development',
                'submission_mode'    => 'captain_only',
                'banner_url'         => null,
                'scoring_type_id'    => $judgeScoreId,
                'registration_fee'   => 120000,
                'quota'              => null,
                'start_date'         => '2026-07-01',
                'end_date'           => '2026-07-20',
                'registration_start' => '2026-05-15',
                'registration_end'   => '2026-07-10',
                'status'             => 'open',
                'rules'              => "1. Android atau iOS dibolehkan\n2. Source code disertakan",
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'uuid'               => Str::uuid(),
                'user_id'            => $felicia,
                'name'               => 'Cyber Security CTF Junior',
                'description'        => 'CTF khusus untuk peserta pemula (High School).',
                'type'               => 'individual',
                'category'           => 'Capture The Flag',
                'submission_mode'    => 'captain_only',
                'banner_url'         => null,
                'scoring_type_id'    => $timeBasedId,
                'registration_fee'   => 0,
                'quota'              => 200,
                'start_date'         => '2026-05-10',
                'end_date'           => '2026-05-11',
                'registration_start' => '2026-04-10',
                'registration_end'   => '2026-05-01',
                'status'             => 'finished',
                'rules'              => "1. Khusus pelajar SMA/SMK\n2. Format flag CTFJR{...}",
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
        ];

        DB::table('competitions')->insert($competitions);
    }
}
