<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            // Committee / Panitia
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Valentino Hose',
                'email'             => 'valentino@competehub.com',
                'password'          => Hash::make('password'),
                'role'              => 'committee',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Felicia Ivanna',
                'email'             => 'felicia@competehub.com',
                'password'          => Hash::make('password'),
                'role'              => 'committee',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            // Judge / Juri
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Jeryko Farelin',
                'email'             => 'jeryko@competehub.com',
                'password'          => Hash::make('password'),
                'role'              => 'judge',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Rico Dharmawan',
                'email'             => 'rico@competehub.com',
                'password'          => Hash::make('password'),
                'role'              => 'judge',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            // Participants / Peserta
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Budi Santoso',
                'email'             => 'budi@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Siti Rahayu',
                'email'             => 'siti@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Andi Wijaya',
                'email'             => 'andi@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Dewi Kusuma',
                'email'             => 'dewi@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Reza Pratama',
                'email'             => 'reza@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'suspended', // untuk test AccountStatusHandler
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Nina Kartika',
                'email'             => 'nina@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Ahmad Zaki',
                'email'             => 'zaki@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Dian Sastro',
                'email'             => 'dian@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Eko Prasetyo',
                'email'             => 'eko@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Fitri Handayani',
                'email'             => 'fitri@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Gunawan Wibisono',
                'email'             => 'gunawan@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Hendra Wijaya',
                'email'             => 'hendra@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Indah Permata',
                'email'             => 'indah@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Joko Susilo',
                'email'             => 'joko@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Lestari Ningsih',
                'email'             => 'lestari@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Mulyadi Pratama',
                'email'             => 'mulyadi@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Nurul Huda',
                'email'             => 'nurul@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Oki Setiawan',
                'email'             => 'oki@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Rian Hidayat',
                'email'             => 'rian@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Sisca Amelia',
                'email'             => 'sisca@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Taufik Hidayat',
                'email'             => 'taufik@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            // More Judges
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Hassan Basri',
                'email'             => 'hassan@competehub.com',
                'password'          => Hash::make('password'),
                'role'              => 'judge',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Lina Marlina',
                'email'             => 'lina@competehub.com',
                'password'          => Hash::make('password'),
                'role'              => 'judge',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            // More Participants
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Yusuf Mansur',
                'email'             => 'yusuf@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Kartika Sari',
                'email'             => 'kartika@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Bambang Pamungkas',
                'email'             => 'bambang@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Cahyo Adi',
                'email'             => 'cahyo@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Doni Salmanan',
                'email'             => 'doni@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Elisa Putri',
                'email'             => 'elisa@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Fajar Alfian',
                'email'             => 'fajar@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Gita Gutawa',
                'email'             => 'gita@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Haris Azhar',
                'email'             => 'haris@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Irma Suryani',
                'email'             => 'irma@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Joni Kemod',
                'email'             => 'joni@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Kiki Amelia',
                'email'             => 'kiki@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Lucky Hakim',
                'email'             => 'lucky@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Mega Utami',
                'email'             => 'mega@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'name'              => 'Nova Eliza',
                'email'             => 'nova@gmail.com',
                'password'          => Hash::make('password'),
                'role'              => 'participant',
                'status'            => 'active',
                'email_verified_at' => now(),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
        ];

        DB::table('users')->insert($users);
    }
}
